### ISSUE TITLE
fix: error when mason make r13n

### ISSUE THREAD

**Issue by lsaudon** [VeryGoodOpenSource/r13n#26]
**Description**

**Steps To Reproduce**

1. Create a flutter app
2. Add r13n package
3. Run `mason make r13n --on-conflict overwrite`
  ```sh
  The current version of "brick:r13n" requires "package:r13n" >=0.1.0-dev.1 <0.1.0-dev.3.
  Because the current version of "package:r13n" is ^0.1.0-dev.3, version solving failed.
  ```

**Expected Behavior**

No error.

**Additional Context**

`Flutter (Channel stable, 3.3.7, on Microsoft Windows [version 10.0.22621.755], locale fr-FR)`

**Comment by wolfenrain** [comment]
I have been able to reproduce this issue, will look into it further to see what is going on
