### ISSUE TITLE
refactor: decompose hooks into multiple files

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/r13n#29]
Upgrade to mason 0.1.0-dev.39 and decompose the hooks into multiple files.

**Comment by alestiago** [comment]
How do we want to proceed with the decomposition?

I've taken a look at both the pre and post generation hooks and tagged them depending on their responsabilities:

| Class                        | Description                                                                                                                           | Tag  |
|------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|------|
| R13nConfiguration            | Class that when constructed, parses the configurable properties from r13n.yaml                                                        | R13n |
| R13nException                | Abstract class to be implemented by errors than can be thrown by r13n.                                                                | R13n |
| ArbValue                     | Class to define an arb value. Currently key, value but can have additional logic to support the additional feature arb has over json. | Arb  |
| ArbDocument                  | Class, that stores data related to a parsed .arb file.                                                                                | Arb  |
| YamlNotFoundException        | Exception that R13nConfiguration throws when there is no r13n.yaml to read the configuration from. Implements R13nException.          | R13n |
| ArbMissingRegionTagException | Exception that ArbDocument throws when parsing an .arb document with no @@region value. Implements R13nException.                     | R13n |
| R13nCompatibilityException   | Exception that may be thrown by the procedure ensureRuntimeCompatibility when the brick:r13n version is not compatible with package:r13n.                     | R13n |

I think ideally the following changes would be ideal:
- Create a package `arb` that has `ArbDocument` and `ArbValue`. The `ArbDocument` should be subclassed in a file `bricks/r13n/hooks/r13n_arb_document.dart` that adds logic to ensure a @@region value is included and throw an `ArbMissingRegionTagException` if not provided.
- Create a new file `bricks/r13n/hooks/r13n_configuration.dart` to include `R13nConfigurartion`.
- Create a new fiel `bricks/r13n/hooks/r13n_exception.dart` to include the abstract class `R13nException`.
- `YamlNotFoundException` should be renamed to `R13nYamlNotFoundException` and moved to `bricks/r13n/hooks/r13n_configuration.dart`.
- Create a new file `bricks/r13n/hooks/r13n_version_compatibility.dart` and move `R13nCompatibilityException` there together with the `ensureRuntimeCompatibility` method.
- Create a package `process_overrides` and move `ProcessOverrides` there.

Wdyt? About the above suggested changes? 

(cc: @wolfenrain , @felangel , @renancaraujo )

**Comment by renancaraujo** [comment]
@B0berman can you comment on this so we can assign you?
