### ISSUE TITLE
chore: bump min Dart SDK version to 2.19.0

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/r13n#47]
**Description**

As a user I would like r13n to be up to date with the most modern Dart SDK.
As a maintainer I would like r13n to use the newest min Dart SDK in order to improve the code with the latest functionalities.

**Additional context**

The current supported Dart SDK is 2.18.0. The Flutter SDK 3.3.0 used 2.18.0 and it was released on 30/08/2022. The Flutter SDK 3.7.0 uses Dart SDK 2.19.0 and it was released on 24/01/2023.

See also:

- https://docs.flutter.dev/development/tools/sdk/releases
- https://github.com/VeryGoodOpenSource/r13n/pull/45#discussion_r1151683569 (Comment by @wolfenrain)

**Comment by tomarra** [comment]
Bumping this up so maybe we update to Dart 3.2 given the latest updates released this week.

**Comment by tomarra** [comment]
Closing this out given the conversation with the team today. Given that we support up to 3 (and technically up to 4 due to compatibility mode) there is no need to make this change currently.
