### ISSUE TITLE
feat: support Mobile Country Code (MCC)

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/r13n#51]
**Description**

Currently, r13n supports `Region.fromPlatform` this sets the region to the one configured by the user within their settings Region.

As a developer, I would like to have something as `Region.fromMobileCountryCode` to return the value of MCC (Mobile Country Code).

- https://developer.apple.com/documentation/coretelephony/ctcarrier/1620309-mobilecountrycode
- https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkOperator()

**Comment by tomarra** [comment]
Unfortunately this data is starting to be used for tracking purposes so the platform providers are going to be pulling it out of the API at some point. Apple has already started as the linked documentation is actually deprecated after iOS 16. Given that, closing this out as a "won't fix" as there doesn't seem to be a big need for this feature as well.
